// <auto-generated />
using System;
using CourseManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Course_Management.Migrations
{
    [DbContext(typeof(CourseManagementDbContext))]
    partial class CourseManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CourseManagement.Models.DangKiKhoaHoc", b =>
                {
                    b.Property<string>("MaHocVien")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaKhoaHoc")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaHocVien", "MaKhoaHoc");

                    b.ToTable("DangKiKhoaHocs");
                });

            modelBuilder.Entity("CourseManagement.Models.HocVien", b =>
                {
                    b.Property<string>("MaHocVien")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .HasColumnType("longtext");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext");

                    b.HasKey("MaHocVien");

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("CourseManagement.Models.KhoaHoc", b =>
                {
                    b.Property<string>("MaKhoaHoc")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GiangVien")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LinhVuc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<int>("SoLuongSinhVienToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiGianKhaiGiang")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KhoaHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
